version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "5858:5858"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ../dummy-data/:/data/db
    ports:
      - "27017:27017"
